name: Deploy JSON Resume to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install resume-cli and custom theme
        run: |
          npm install -g resumed jsonresume-theme-ludoo
      - name: Generate HTML resume
        run: resumed render --theme jsonresume-theme-ludoo -o public/index.html
      - name: Remove col-sm-offset-1 class
        run: |
          sed -i 's/class="col-sm-offset-1/class="/g' public/index.html
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
